[package]
name = "preflight_native"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
graphics = { path = "../../graphics_wgpu" }
egui = "^0.19.0"
lin-alg2 = { path = "../../lin_alg"}
# To parse enums from their integer repr
serialport = "^4.2.0"
num_enum = { version = "0.5.7", default_features = false }
